name: Build and Push Backend Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: dilzhan/ecommerce-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print Docker Hub Login Status
        run: |
          echo "Logged in as ${{ secrets.DOCKERHUB_USERNAME }}"
          docker info

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Verify Image
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}:latest
          docker image inspect ${{ env.DOCKER_IMAGE }}:latest

      - name: Image Push Status
        if: success()
        run: |
          echo "✅ Image successfully pushed to Docker Hub"
          echo "Image: ${{ env.DOCKER_IMAGE }}:latest"
          echo "Image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}" 